In [2]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path('../data/raw/twcs_subsample.csv')
df = pd.read_csv(DATA_PATH)

df.shape

(200000, 7)

In [3]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [4]:
brand_counts = df[df["inbound"]==False]["author_id"].value_counts()
brand_counts.head(20)

author_id
AmazonHelp         15323
AppleSupport        5511
Uber_Support        3609
SpotifyCares        2674
Delta               2284
Tesco               2239
AmericanAir         2077
British_Airways     2034
comcastcares        1946
hulu_support        1861
XboxSupport         1840
TMobileHelp         1729
VirginTrains        1671
ChipotleTweets      1571
idea_cares          1504
sainsburys          1494
AskPlayStation      1419
SouthwestAir        1410
O2                  1371
sprintcare          1350
Name: count, dtype: int64

In [5]:
is_apple_reply = df["author_id"] == "AppleSupport"
is_customer_to_apple = (df["inbound"]==True) & (df["text"].str.contains("@AppleSupport",case=False, na=False))

apple_df = df[is_apple_reply | is_customer_to_apple].copy()
apple_df.shape

(10883, 7)

In [6]:
customer_msgs = apple_df[apple_df["inbound"]==True]
brand_replies = apple_df[apple_df["inbound"]==False]

pairs = customer_msgs.merge(
    brand_replies,
    left_on="tweet_id",
    right_on="in_response_to_tweet_id",
    suffixes=("_customer","_apple")
)
pairs[["text_customer","text_apple"]].head(10)

,text_customer,text_apple
0,@AppleSupport The newest update. I️ made sure ...,@115854 Lets take a closer look into this issu...
1,@AppleSupport https://t.co/NV0yucs0lB,@115854 We're here for you. Which version of t...
2,@AppleSupport Tried resetting my settings .. r...,@115855 Let's go to DM for the next steps. DM ...
3,@AppleSupport This is what it looks like https...,@115855 Any steps tried since it started last ...
4,@AppleSupport I️ have an iPhone 7 Plus and yes...,@115855 That's great it has iOS 11.1 as we can...
5,@AppleSupport I️ need answers because it’s ann...,@115855 We'd like to look into this with you. ...
6,Hey @AppleSupport and anyone else who upgraded...,"@115856 Hey, let's work together to figure out..."
7,@AppleSupport This is what is happening... htt...,@115857 We'd like to investigate further with ...
8,@AppleSupport are the call centres closed for ...,@115859 We've received your DM and will contin...
9,@115858 @AppleSupport hello are all the lines ...,@115859 What's going on? We're hapy to help if...

In [7]:
sample_for_taxonomy = pairs.sample(n=60,random_state=42)[["text_customer","text_apple"]]
sample_for_taxonomy.to_csv("../data/taxonomy_reading_sample.csv", index=False)
sample_for_taxonomy

,text_customer,text_apple
2776,@AppleSupport No tried that a few times... it’...,@149735 OK thanks for trying that. What versio...
3022,@AppleSupport I need help with something relat...,@151821 We'd be happy to help. What's going on...
2606,"@AppleSupport Team, I tried configuring “Hey S...","@148935 Hey there, we understand you're having..."
912,@AppleSupport And i cant fix it i had to turn ...,@125900 Let's get this figured out. Which iOS ...
877,@AppleSupport is it possible to get a 2011 Mac...,@125602 Let's see what we can find out. Send u...
151,@AppleSupport iOS11.1 consumes battery pretty ...,@117645 Let's see how you're using your batter...
3207,@AppleSupport And are people trying to hack my...,@154492 While we can't know if someone is tryi...
3762,@AppleSupport The second one. The battery life...,@162083 We're here to help. DM us the exact iO...
2722,"@AppleSupport When someone calls me, the conta...",@149697 Is this the same contact photo you use...
3653,Can we get good quality charger cables? These ...,@160234 We'd like to look in to your options w...
109,@AppleSupport Updated iPad Pro to 11.1. Worke...,@117107 We'll help in any way we can. Was this...
4114,"Depois que atualizei o aparelho para iOS 11 , ...",@167172 Since our Twitter support is available...
2749,@AppleSupport my case is still open. More then...,@149717 Meet us in DM and we'll point you in t...
2005,"@AppleSupport Thanks. Yep I checked that, but ...",@138973 We'd like to look into this further. P...
149,@AppleSupport It’s showing it’s connected and ...,@117641 We are here for you. Let's take a look...
3095,@AppleSupport It will verify for a good few mi...,@153199 Alright. Let's go ahead and try each o...
120,@115858 after the new apple updates: the batte...,@117189 We'd love to help. Let's work on this ...
1634,@AppleSupport Here we go! Any ideas? https://t...,@135633 We're glad you were able to partially ...
3717,@AppleSupport Thank you! I use the Gmail app f...,@161508 Go ahead and send us a DM please. Let ...
3328,@AppleSupport I think it keeps getting knocked...,@156813 Great. Send us a DM if you are still h...
4352,@AppleSupport still haven't got IOS 11 to dow...,"@171698 Absolutely, we’d be happy to help! Are..."
3740,"@AppleSupport iOS 11 bug. Bluetooth turn off, ...",@161526 Thank you for reaching out to us about...
2420,@AppleSupport Restarting the phone does not wo...,"@143489 Got it, thanks! Recently we did releas..."
1909,@AppleSupport Latest iOS. Has always happened ...,@137635 We'd be happy to look into this with y...
1370,@AppleSupport 11.0.2 is newest version accordi...,@130561 Thanks for that info. The iOS version ...
3262,before they update any other pointless thing @...,@155694 We appreciate you getting in touch wit...
3357,Every time I turn my phone on Bluetooth random...,@157387 We'd be happy to help out with this. L...
1702,@AppleSupport I just bought a new iPhone 8 Plu...,@136075 Congratulations on your new iPhone 8 P...
2543,@AppleSupport hello I’ve been trying to get ve...,@148419 Hi there! You caught us while we were ...
463,Can y’all fix the I character please?! I️m tir...,@123182 We'd like to work on this with you. Wh...
1055,@AppleSupport It freezes constantly having pro...,@127755 Got it. Please DM us and we will conti...
596,@AppleSupport suspect fraud for you to look in...,@123699 We can help. This looks like a phishin...
3286,The update to macOS High Sierra sucks. It has ...,@156115 We’d like to understand more about thi...
3941,@AppleSupport I have a question,@165259 How can we assist? Let us know the det...
4207,"this new apple update is horrible, my phones b...",@166006 Let's work together to get your device...
3220,@AppleSupport I will send a message to someone...,@154903 Hi there. We'd like to look into this....
297,Anyone else having battery issues in IPhone? D...,"@119400 Having a reliable iPhone is important,..."
1600,"@AppleSupport Thanks for the lead, but still g...",@135604 Let's look into this a bit deeper. Let...
4022,@AppleSupport Your new update is killing my ba...,"@165822 We're here for you! Send us a DM, and ..."
415,@AppleSupport Battery draining in recent updat...,"@123039 We've received your DM, and we'll cont..."
3919,@AppleSupport Issue started when I updated my ...,@165241 Thanks for the update. Reach us via DM...
3450,@AppleSupport Yes,@158626 Thanks. Follow the steps here to chang...
179,@applesupport just updated Apple Watch to 4.1....,@117961 We want to help you. That station may ...
1714,@AppleSupport @115858 sometimes I get these em...,@136089 We can assist you. The following guide...
2086,@AppleSupport The newest one,@140201 Got it. We've received your DM and you...
2258,"@AppleSupport I updated my phone, and it’s sti...",@141849 Meet us in DM and fill us in in as muc...
3641,@AppleSupport do you want to tell me what’s go...,@160220 We're here to help. Which iOS version ...
3996,@AppleSupport Now when I restart my phone it w...,"@165458 Got it, thanks! So we can provide you ..."
2770,@AppleSupport my phone has turned itself off a...,@149733 We can help get your iPhone up and run...
2101,@AppleSupport Turned it off and in again and n...,@140211 We're glad to hear that it's working. ...
3462,"@AppleSupport Hi Team,\nExperiencing a very ba...",@159394 Thanks for reaching out to us here. We...
3468,@AppleSupport so annoying that I can’t send e-...,@159401 We know how important emailing is so y...
2042,"Hey @AppleSupport, wanna explain to me why my ...",@139283 We can help! Are you using iOS 11? If ...
4084,"@AppleSupport Thanks! iPad Air 2 (MGWL2X/A), 1...","@166053 Great, thanks! At this time, we'd like..."
4148,"@AppleSupport, is there a reason some of my em...",@167315 Let's look into that. Send us a DM and...
17,@AppleSupport iPhone 7 Plus 😊,@115865 Thanks! Which iOS version is currently...
598,"Hello,i have a question but i'm not sure is th...",@123702 Hello! You'll want to work with our En...
2577,@AppleSupport suddenly my back camera of iPhon...,@148902 We've received your DM and will contin...
2446,1 semaine et mon iPhone tombe vraiment en ruin...,@143657 We offer support via Twitter in Englis...
1057,@AppleSupport Seems to turn on randomly while ...,@127757 Check out this link for more informati...